// Action types for the application
export const SEARCH_FLIGHTS = 'SEARCH_FLIGHTS';
export const SEARCH_FLIGHTS_SUCCESS = 'SEARCH_FLIGHTS_SUCCESS';
export const SEARCH_FLIGHTS_FAILURE = 'SEARCH_FLIGHTS_FAILURE';
export const SELECT_FLIGHT = 'SELECT_FLIGHT';
export const BOOK_FLIGHT = 'BOOK_FLIGHT';
export const BOOK_FLIGHT_SUCCESS = 'BOOK_FLIGHT_SUCCESS';
export const BOOK_FLIGHT_FAILURE = 'BOOK_FLIGHT_FAILURE';
export const GET_FLIGHT_LIST = 'GET_FLIGHT_LIST';
export const GET_FLIGHT_LIST_SUCCESS = 'GET_FLIGHT_LIST_SUCCESS';
export const GET_FLIGHT_LIST_ERROR = 'GET_FLIGHT_LIST_ERROR';
export const RESET_FLIGHT_LIST = 'RESET_FLIGHT_LIST';
export const SET_BOOKING_DETAILS = 'SET_BOOKING_DETAILS';

// Default export - object containing all actions
export default {
  SEARCH_FLIGHTS,
  SEARCH_FLIGHTS_SUCCESS,
  SEARCH_FLIGHTS_FAILURE,
  SELECT_FLIGHT,
  BOOK_FLIGHT,
  BOOK_FLIGHT_SUCCESS,
  BOOK_FLIGHT_FAILURE,
  GET_FLIGHT_LIST,
  GET_FLIGHT_LIST_SUCCESS,
  GET_FLIGHT_LIST_ERROR,
  RESET_FLIGHT_LIST,
  SET_BOOKING_DETAILS
};